instrumentation:
    root: './src'
    include-all-sources: true
reporting:
    print: none
    dir: ./coverage
    watermarks:
        statements: [80, 100]
        lines: [80, 100]
        functions: [80, 100]
        branches: [80, 100]
    reports:
        - json
        - text-summary
        - html
        - lcov
    report-config:
        json: {file: coverage.json}
