'use strict';

module.exports = {
	// TOKEN_TYPE
	TOKEN_TYPE_STRUCTURE: 'STRUCTURE',
	TOKEN_TYPE_STATEMENT: 'STATEMENT',
	TOKEN_TYPE_BOUNDARY: 'BOUNDARY',
	TOKEN_TYPE_UNARY_OPERATOR: 'UNARY_OPERATOR',
	TOKEN_TYPE_BINARY_OPERATOR: 'BINARY_OPERATOR',
	TOKEN_TYPE_VALUE: 'VALUE',

	TOKEN_STRUCTURE_TEXT_LITERAL: 'TEXT_LITERAL',
	TOKEN_STRUCTURE_EOF: 'EOF',

	TOKEN_STATEMENT_IF: 'IF',
	TOKEN_STATEMENT_ELIF: 'ELIF',
	TOKEN_STATEMENT_ELSE: 'ELSE',
	TOKEN_STATEMENT_FI: 'FI',
	TOKEN_STATEMENT_INCLUDE: 'INCLUDE',

	TOKEN_BOUNDARY_TAG_START: 'TAG_START',
	TOKEN_BOUNDARY_TAG_END: 'TAG_END',
	TOKEN_BOUNDARY_BRACKET_OPEN: 'BRACKET_OPEN',
	TOKEN_BOUNDARY_BRACKET_CLOSE: 'BRACKET_CLOSE',
	TOKEN_BOUNDARY_STRING_SINGLE: 'STRING_SINGLE',
	TOKEN_BOUNDARY_STRING_DOUBLE: 'STRING_DOUBLE',

	TOKEN_OPERATOR_EQUALS: 'EQUALS',
	TOKEN_OPERATOR_NOT_EQUALS: 'NOT_EQUALS',
	TOKEN_OPERATOR_STRICT_EQUALS: 'STRICT_EQUALS',
	TOKEN_OPERATOR_STRICT_NOT_EQUALS: 'STRICT_NOT_EQUALS',
	TOKEN_OPERATOR_AND: 'AND',
	TOKEN_OPERATOR_OR: 'OR',
	TOKEN_OPERATOR_NOT: 'NOT',
	TOKEN_OPERATOR_GREATER_THAN: 'GREATER_THAN',
	TOKEN_OPERATOR_LESS_THAN: 'LESS_THAN',
	TOKEN_OPERATOR_GREATER_EQUAL_THAN: 'GREATER_EQUAL_THAN',
	TOKEN_OPERATOR_LESS_EQUAL_THAN: 'LESS_EQUAL_THAN',

	TOKEN_VALUE_VARIABLE: 'VARIABLE',
	TOKEN_VALUE_STRING: 'STRING',
	TOKEN_VALUE_INTEGER: 'INTEGER',
	TOKEN_VALUE_FLOAT: 'FLOAT'
};
